# Site settings
title: My Portfolio
description: Portfolio of Yumeng Zhang
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site

# User settings
username: Yumeng Zhang
user_description: 
  Hi, Yumeng here, but Natalie is what my friends call me. I am currently a second year double degree student studying Computer Science 
  at the University of Waterloo and Business Administration at Wilfrid Laurier University.
  I always bring 100% to the work I do and I am not afraid to take initiatives and seek new challenges. 
user_title: Student, Software Developer
email: y2388zha@edu.uwaterloo.ca
twitter_username: neyclesley
github_username:  Nataland
gplus_username:  neyclesley

# Google-analytics
google-analytics:
  id: "UA-121083768-1"

exclude: ['package.json', 'src' , 'node_modules']
